image: "rust:latest"

before_script:
    - apt update -yqq
    - apt install -yqq --no-install-recommends libgtk-3-dev

lint:fmt:
    before_script:
        - rustup component add rustfmt-preview
    script:
        - cargo fmt
        - if $(git ls-files --modified | wc -l) -ne 0
          then
            echo 'You have introduced some unformated code:';
            git ls-files --modified | sed 's/^/* /';
            echo 'Please run `cargo fmt` and amend your PR.';
            exit 1;
          fi

lint:clippy:
    script:
        - rustup component add clippy
        - cargo clippy -- --deny warnings

test:debug:
    script: make MODE=debug test

test:release:
    script: make MODE=release test
