[package]
name = "effitask"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
homepage = "https://github.com/sanpii/effitask"

[dependencies]
cairo-rs = "^0.4"
chrono = "^0.4"
gdk = "^0.8"
gdk-sys = "^0.6"
glib = "^0.5"
human-panic = "^0.4"
pulldown-cmark = "^0.1"
rand = "^0.4"
regex = "^1.0"
relm = "^0.14"
relm-attributes = "^0.14"
relm-derive = "^0.14"
todo-txt = "^1.0"
xdg = "^2.1"

[dependencies.gtk]
version = "0.4"
features = ["v3_22"]

[dependencies.log]
version = "^0.4"
features = ["std"]

[dependencies.clippy]
version = "*"
optional = true

[features]
default = ["relm/unstable", "relm-attributes/unstable", "relm-derive/unstable"]

[badges]
gitlab = { repository = "sanpi/effitask", branch = "master" }
