[package]
name = "effitask"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
chrono = "^0.4"
env_logger = "^0.4"
log = "^0.3"
relm = "^0.11"
relm-attributes = "^0.11"
relm-derive = "^0.11"
todo-txt = "^0.7"

[dependencies.gtk]
version = "0.3"
features = ["v3_22"]
