[package]
name = "effitask"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
cairo-rs = "^0.3"
chrono = "^0.4"
gdk = "^0.7"
gdk-sys = "^0.5"
glib = "^0.4"
log = "^0.3"
rand = "^0.3"
regex = "^0.2"
relm = "^0.11"
relm-attributes = "^0.11"
relm-derive = "^0.11"
todo-txt = "^0.7"
xdg = "^2.1"

[dependencies.gtk]
version = "0.3"
features = ["v3_22"]

[dependencies.clippy]
version = "*"
optional = true
